### ISSUE TITLE
OcuJoy immediately closes itself when opened

### ISSUE THREAD

**Issue by MrPresidentBanana** [lyneca/ocujoy#2]
Whenever I open OcuJoy, I can see a command prompt window for a split second before it closes itself again. I've reinstalled both vJoy and OcuJoy and made sure the former is properly configured, but this doesn't seem to fix it. The weird thing is, it worked fine just yesterday. I attempted to use it with DCS, but the axis' were all assigned wrong. Today I fixed that (didn't do anything in the .binds file, only the DCS controls settings), but now OcuJoy does this.

**Comment by Cpainy** [comment]
It took me some time to get this app to work, but when it does it works great. Thanks!
Some things maybe to add in help file:
The Vjoy software had installer problems. I first needed to install the latest version from their github. Only after that I could install the soundforce version you link to. Didn't test if you can do it with github version (has different version number).

Ocujoy.exe needs to be in this folder "C:\Program Files\vJoy\x64" or it won't find the dll.
And you need to start ocujoy first, before starting vjoy, or as @MrPresidentBanana  said, it just closes.

Hopes that fixes it for you @MrPresidentBanana

**Comment by jhbeskow** [comment]
Agree with @Cpainy.  It was closing immediately for me until I dropped it inside the vJoy install folder.  I then created a shortcut to launch OcuJoy.

**Comment by forthro** [comment]
I have the same immediate close problem, although I think it's a different root cause.  My headset (Quest 2) is working fine through SteamVR.  Here's the error I get:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ovrErrorInfo { Result: -1007, ErrorString: "ovr_Create: No HMD attached." }', src/bin.rs:496:77
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by bgeck** [comment]
> I have the same immediate close problem, although I think it's a different root cause. My headset (Quest 2) is working fine through SteamVR. Here's the error I get:
> 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ovrErrorInfo { Result: -1007, ErrorString: "ovr_Create: No HMD attached." }', src/bin.rs:496:77 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I ran into the same issue and I only got it to work via the following:

- Make sure to connect your headset to your PC with Oculus Link or Air Link. I was trying to get it to work with Virtual Desktop but because that doesn't detect the device in "ovr", that is why it wasn't working seems like. Makes sense if ocujoy is "hooking" in to the ovr runtime.
-
- So far I've only been able to get it to detect when using the PC via Oculus Link. Going to look into how one might go about expanding it to detect HMD using other methods like Virtual Desktop or SteamVR
